version: '3.3'

services:
  db:
    container_name: cashforce-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cashforce-db
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306